#!/usr/bin/env php
<?php

/**
 * |----------------------------------------------------------------
 * |             ***** Composer Auto Loader *****
 * |----------------------------------------------------------------
 */
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$app->make();
$app->run();
